version: '3.8'
name: 'zoo-backend'
services:
  zoo-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: zoo-app
    env_file:
      - ../.env
    ports:
      - '3000:3000'
    volumes:
      - ../src:/app/src
